version: '2'

services:
  analyser:
    build: .
    environment:
      DATABASE: ${DATABASE}
      NEWS_API_KEY: ${NEWS_API_KEY}
      DB_USER: ${GOOD_NEWS_DB_USER}
      DB_PASSWORD: ${GOOD_NEWS_DB_PASSWORD}
      DB_HOST: ${GOOD_NEWS_DB_HOST}

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${GOOD_NEWS_DB_PASSWORD}
      MYSQL_PASSWORD: ${GOOD_NEWS_DB_PASSWORD}
      MYSQL_DATABASE: good_news
    restart: always